### ISSUE TITLE
Change domain used in status emails

### ISSUE THREAD

**Issue by ThomasSingleton** [OneUptime/oneuptime#1951]
**Is your feature request related to a problem? Please describe.**
Installation URL is used in status emails instead of status page custom domain

**Describe the solution you'd like**
Make it possible to use custom domain

Our instance is hosted at uptime.example.com, and links with that domain are getting sent to status page subscribers, when the links should go to statuspage.example.com, where the status page is hosted

**Additional context**

![Image](https://github.com/user-attachments/assets/a9890371-2b10-44b7-b0e7-4ada73fadca2)

**Comment by simao-silva** [comment]
Any updates on this?

**Comment by simlarsen** [comment]
Fixed in the next release. EOD today.

**Comment by simao-silva** [comment]
@simlarsen in which release was this fixed? I am still not seeing this fix.

**Comment by simlarsen** [comment]
@simao-silva Can you please recheck? In whcih cases are you not seeing a fix?
