### ISSUE TITLE
Notification emails are sent twice

### ISSUE THREAD

**Issue by ThoSt81** [OneUptime/oneuptime#2149]
**Describe the bug**
We have noticed that for some time now, the email notifications for an event (incident, scheduled maintenance) are sent multiple times. We dont think this is an error due to miss configuration but rather a bug.

This seems to be happening since some time in November.

**To Reproduce**
1. Create a new incident/scheduled event
2. Transition through states
3. check notifciation log or feed on overview page

**Expected behavior**
Notifications should only be sent once per subscriber and eventupdate

**Screenshots**

<img width="831" height="289" alt="Image" src="https://github.com/user-attachments/assets/02c65c45-dce6-4a06-b6b9-0103fe69c44e" />

<img width="1029" height="247" alt="Image" src="https://github.com/user-attachments/assets/2dc6c0df-49b0-4441-adb2-c6fd0c62d9af" />

**Comment by simlarsen** [comment]
This is resolved and will be released later today.

**Comment by ThoSt81** [comment]
@simlarsen can you confirm when this was rolled out? We have added a public note this morning (08:13 CET) and this again appeard to have caused double notifications at (08:17 CET).

**Comment by ThoSt81** [comment]
@simlarsen We still appear to have an issue here:

[Scheduled Maintenance Ended] was sent once.
[Scheduled Maintenance Ongoing] was sent twice to every subscriber this morning.

Could you please check? Thank you!

**Comment by simlarsen** [comment]
@ThoSt81 We have identified this issue and will be fixed today.
