### ISSUE TITLE
Not possible to open criteria edit

### ISSUE THREAD

**Issue by nalognl** [OneUptime/oneuptime#460]
**Describe the bug**
Not possible to open criteria edit

**To Reproduce**
1. Go to 'View Monitor'
2. Click on 'Criteria'
3. Page is empty

**Expected behavior**
Possibility to edit criteria

**Screenshots**
![image](https://github.com/OneUptime/oneuptime/assets/59573488/e1e5155c-4035-4629-b8df-58403d3e598a)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Google Chrome
 - Version Versie 113.0.5672.127 (Officiële build) (64-bits)

**Additional context**
criteria:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

react-dom.production.min.js:189 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B_route%2C%20_params%2C%20_protocol%2C%20_hostname%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at th (react-dom.production.min.js:152:54)
    at J (react-dom.production.min.js:162:372)
    at Yi (react-dom.production.min.js:192:291)
    at Wk (react-dom.production.min.js:294:1)
    at Vk (react-dom.production.min.js:280:383)
    at Uk (react-dom.production.min.js:280:319)
    at Jk (react-dom.production.min.js:280:180)
    at Ok (react-dom.production.min.js:271:86)
    at Hk (react-dom.production.min.js:268:399)
    at J (scheduler.production.min.js:13:197)
Mi @ react-dom.production.min.js:189
Oi.c.callback @ react-dom.production.min.js:189
ih @ react-dom.production.min.js:144
lk @ react-dom.production.min.js:262
jk @ react-dom.production.min.js:260
ik @ react-dom.production.min.js:259
Xk @ react-dom.production.min.js:283
Qk @ react-dom.production.min.js:281
Hk @ react-dom.production.min.js:269
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
react-dom.production.min.js:152 Uncaught Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B_route%2C%20_params%2C%20_protocol%2C%20_hostname%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at th (react-dom.production.min.js:152:54)
    at J (react-dom.production.min.js:162:372)
    at Yi (react-dom.production.min.js:192:291)
    at Wk (react-dom.production.min.js:294:1)
    at Vk (react-dom.production.min.js:280:383)
    at Uk (react-dom.production.min.js:280:319)
    at Jk (react-dom.production.min.js:280:180)
    at Ok (react-dom.production.min.js:271:86)
    at Hk (react-dom.production.min.js:268:399)
    at J (scheduler.production.min.js:13:197)
    
    Manifest: Line: 1, column: 1, Syntax error.

**Comment by tankerkiller125** [comment]
I'm also experiencing this issue (self-hosted). This issue does not appear for Manual monitors (it correctly states that they don't support it), but for all other types of monitors I get an error. This error doesn't seem to happen on the hosted version.

Full console output when I attempt to navigate to the Criteria edit page:
```
(index):64  cdn.tailwindcss.com should not be used in production. To use Tailwind CSS in production, install it as a PostCSS plugin or use the Tailwind CLI: https://tailwindcss.com/docs/installation
(anonymous) @ (index):64
ma:1  Manifest: Line: 1, column: 1, Syntax error.
react-dom.production.min.js:189  Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B_route%2C%20_params%2C%20_protocol%2C%20_hostname%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at th (react-dom.production.min.js:152:54)
    at J (react-dom.production.min.js:162:372)
    at Yi (react-dom.production.min.js:192:291)
    at Wk (react-dom.production.min.js:294:1)
    at Vk (react-dom.production.min.js:280:383)
    at Uk (react-dom.production.min.js:280:319)
    at Jk (react-dom.production.min.js:280:180)
    at Ok (react-dom.production.min.js:271:86)
    at Hk (react-dom.production.min.js:268:399)
    at J (scheduler.production.min.js:13:197)
Mi @ react-dom.production.min.js:189
Oi.c.callback @ react-dom.production.min.js:189
ih @ react-dom.production.min.js:144
lk @ react-dom.production.min.js:262
jk @ react-dom.production.min.js:260
ik @ react-dom.production.min.js:259
Xk @ react-dom.production.min.js:283
Qk @ react-dom.production.min.js:281
Hk @ react-dom.production.min.js:269
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
react-dom.production.min.js:152  Uncaught Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B_route%2C%20_params%2C%20_protocol%2C%20_hostname%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at th (react-dom.production.min.js:152:54)
    at J (react-dom.production.min.js:162:372)
    at Yi (react-dom.production.min.js:192:291)
    at Wk (react-dom.production.min.js:294:1)
    at Vk (react-dom.production.min.js:280:383)
    at Uk (react-dom.production.min.js:280:319)
    at Jk (react-dom.production.min.js:280:180)
    at Ok (react-dom.production.min.js:271:86)
    at Hk (react-dom.production.min.js:268:399)
    at J (scheduler.production.min.js:13:197)
th @ react-dom.production.min.js:152
J @ react-dom.production.min.js:162
Yi @ react-dom.production.min.js:192
Wk @ react-dom.production.min.js:294
Vk @ react-dom.production.min.js:280
Uk @ react-dom.production.min.js:280
Jk @ react-dom.production.min.js:280
Ok @ react-dom.production.min.js:271
Hk @ react-dom.production.min.js:268
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
```

**Comment by simlarsen** [comment]
This should now be fixed. Please update to latest

**Comment by tankerkiller125** [comment]
Got the latest version of the application (just 10 minutes ago), and this issue and #461 don't seem to be fixed. Still getting the following in the console:

```
(index):64  cdn.tailwindcss.com should not be used in production. To use Tailwind CSS in production, install it as a PostCSS plugin or use the Tailwind CLI: https://tailwindcss.com/docs/installation
(anonymous) @ (index):64
ma:1  Manifest: Line: 1, column: 1, Syntax error.
react-dom.production.min.js:189  Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B_route%2C%20_params%2C%20_protocol%2C%20_hostname%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at th (react-dom.production.min.js:152:54)
    at J (react-dom.production.min.js:162:372)
    at Yi (react-dom.production.min.js:192:291)
    at Wk (react-dom.production.min.js:294:1)
    at Vk (react-dom.production.min.js:280:383)
    at Uk (react-dom.production.min.js:280:319)
    at Jk (react-dom.production.min.js:280:180)
    at Ok (react-dom.production.min.js:271:86)
    at Hk (react-dom.production.min.js:268:399)
    at J (scheduler.production.min.js:13:197)
Mi @ react-dom.production.min.js:189
Oi.c.callback @ react-dom.production.min.js:189
ih @ react-dom.production.min.js:144
lk @ react-dom.production.min.js:262
jk @ react-dom.production.min.js:260
ik @ react-dom.production.min.js:259
Xk @ react-dom.production.min.js:283
Qk @ react-dom.production.min.js:281
Hk @ react-dom.production.min.js:269
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
react-dom.production.min.js:152  Uncaught Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B_route%2C%20_params%2C%20_protocol%2C%20_hostname%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at th (react-dom.production.min.js:152:54)
    at J (react-dom.production.min.js:162:372)
    at Yi (react-dom.production.min.js:192:291)
    at Wk (react-dom.production.min.js:294:1)
    at Vk (react-dom.production.min.js:280:383)
    at Uk (react-dom.production.min.js:280:319)
    at Jk (react-dom.production.min.js:280:180)
    at Ok (react-dom.production.min.js:271:86)
    at Hk (react-dom.production.min.js:268:399)
    at J (scheduler.production.min.js:13:197)
th @ react-dom.production.min.js:152
J @ react-dom.production.min.js:162
Yi @ react-dom.production.min.js:192
Wk @ react-dom.production.min.js:294
Vk @ react-dom.production.min.js:280
Uk @ react-dom.production.min.js:280
Jk @ react-dom.production.min.js:280
Ok @ react-dom.production.min.js:271
Hk @ react-dom.production.min.js:268
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
```

**Comment by tankerkiller125** [comment]
After clearing cache on my web proxy and what not, these issues are fixed.
